cart/urls.py
from nturl2path import url2pathname
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
    
]

coupons/urls.py
from django.urls import path
from . import views

app_name = "coupons"

urlpatterns = [path("app/", views.coupon_apply, name="apply")]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("", include("shop.urls", namespace="shop")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
    path("create/", views.order_create, name="order_create"),
    path(
        "admin/order/<int:order_id>/",
        views.admin_order_detail,
        name="admin_order_detail",
    ),
    path(
        "admin/order/<int:order_id>/pdf/", views.admin_order_pdf, name="admin_order_pdf"
    ),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"
urlpatterns = [

    path("", views.product_list, name="product_list"),
    path(
        "<slug:category_slug>/",
        views.product_list,
        name="product_list_by_category",
    ),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
    
]

cart/models.py
from decimal import Decimal
from django.conf import settings
from shop.models import Product
from coupons.models import Coupon

# Create your models here.


class Cart(object):
    def __init__(self, request) -> None:
        self.session = request.session
        cart = self.session.get(settings.CART_SESSION_ID)
        if not cart:
            cart = self.session[settings.CART_SESSION_ID] = {}
        self.cart = cart
        self.coupon_id = self.session.get("coupon_id")

    def add(self, product, quantity=1, update_quantity=False):
        product_id = str(product.id)
        if product_id not in self.cart:
            self.cart[product_id] = {"quantity": 0, "price": str(product.price)}

        if update_quantity:
            self.cart[product_id]["quantity"] = quantity
        else:
            self.cart[product_id]["quantity"] += quantity
        self.save()

    def save(self):
        self.session.modified = True

    def remove(self, product):
        product_id = str(product.id)
        if product_id in self.cart:
            del self.cart[product_id]
            self.save()

    def __iter__(self):
        product_ids = self.cart.keys()
        products = Product.objects.filter(id__in=product_ids)

        cart = self.cart.copy()
        for product in products:
            cart[str(product.id)]["product"] = product
        for item in cart.values():
            item["price"] = Decimal(item["price"])
            item["total_price"] = item["price"] * item["quantity"]
            yield item

    def __len__(self):
        return sum(item["quantity"] for item in self.cart.values())

    def get_total_price(self):
        return sum(
            Decimal(item["price"]) * item["quantity"] for item in self.cart.values()
        )

    def clear(self):
        del self.session[settings.CART_SESSION_ID]
        self.save()

    @property
    def coupon(self):
        if self.coupon_id:
            return Coupon.objects.get(id=self.coupon_id)
        return None

    def get_discount(self):
        if self.coupon:
            return (self.coupon.discount / Decimal("100")) * self.get_total_price()
        return Decimal("0")

    def get_total_price_after_coupon(self):
        return self.get_total_price() - self.get_discount()

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=_("Quantity")
    )
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .forms import CartAddProductForm
from .models import Cart
from coupons.forms import CouponApplyForm

# Create your views here.


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, quantity=cd["quantity"], update_quantity=cd["override"]
        )
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(
            initial={"quantity": item["quantity"], "override": True}
        )
    coupon_apply_form = CouponApplyForm()

    return render(
        request,
        "cart/detail.html",
        {"cart": cart, "coupon_apply_form": coupon_apply_form},
    )


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .forms import CartAddProduct
from .models import Cart
# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product= get_object_or_404(Product, id=product_id)
    form = CartAddProduct(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd["quantity"], update_quantity=cd["update"])
    return redirect("cart:cart_detail")

@require_POST
def cart_detail(request):
    cart = Cart(request)
    return render(request,"cart/detail.html", {"cart":cart})
    

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block titile %}
    Koszyk na zakupy
{% endblock titile %}

{% block content %}
    <table class="cart">
        <thead>
            <tr>
                <th>Obraz</th>
                <th>Produkt</th>
                <th>Ilość</th>    
                <th>Usuń</th>
                <th>Cena jednostkowa</th>
                <th>Kwota</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                
                {% with product=item.product %}
                
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png'%}{% endif %}">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{item.update_quantity_form.quantity}}
                                {{item.update_quantity_form.override}}
                                <input type="submit" value="Zmień">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                <input type="submit" value="Usuń">
                                {% csrf_token %}
                            </form>   
                        </td>
                        <td class="num">{{ item.price }} zł</td>
                        <td class="num">{{ item.total_price }} zł</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            {% if cart.coupon %}
            <tr class="subtotal">
              <td>Subtotal</td>
              <td colspan="4"></td>
              <td class="num">{{ cart.get_total_price|floatformat:2 }} zł</td>
            </tr>
            <tr>
              <td>
                Kupon"{{ cart.coupon.code }}"
                ({{ cart.coupon.discount }}% rabatu)
              </td>
              <td colspan="4"></td>
              <td class="num neg">-{{ cart.get_discount|floatformat:2 }} zł</td>
            </tr>
          {% endif %}
          <tr class="total">
            <td>Suma</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price_after_coupon|floatformat:2 }} zł</td>
          </tr>
        </tbody>
    </table>
    <p>Kupon rabatowy:</p>
    <form action="{% url "coupons:apply" %}" method="post">
        {{ coupon_apply_form}}
        <input type="submit" value="Wprowadź">
        {% csrf_token %}
    </form>
    <p class="text-right">
        <a href="{% url "shop:product_list"%}" class="button light">Kontynuuj zakupy</a>
        <a href="{% url "orders:order_create" %}" class="button">Do klasy</a>
        
                    
{% endblock content %}